Pcompany_task/Controllers/Category_MasterController.cs
using Pcompany_task.Data_Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pcompany_task.Controllers
{
    public class Category_MasterController : Controller
    {
        // GET: Category_Master
        public ActionResult Index()
        {
            return View();
        }
      
        public ActionResult Save(Category ctg)
        {

            using (Pcompany_taskEntities db = new Pcompany_taskEntities())
            {

                if (ctg.Id == 0)
                {
                    var obj = new Category();
                    obj = db.Categories.Where(x => x.Category1 == ctg.Category1).FirstOrDefault();
                    if (obj == null)
                    {
                        Category _catg = new Category()
                        {
                            Category1 = ctg.Category1,
                        };
                        db.Entry(ctg).State = System.Data.Entity.EntityState.Added;
                        db.SaveChanges();
                    }
                    else
                    {
                        TempData["Error"] = "Oops Something wrong !!!";
                    };
                }
                else
                {
                    Category _catg = new Category()
                    {
                        Id = ctg.Id,
                        Category1 = ctg.Category1,
                    };
                    db.Entry(ctg).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                }
            }

            return RedirectToAction("Index");
        }
        public ActionResult Report()
        {
            using (Pcompany_taskEntities db = new Pcompany_taskEntities())
            {
                return View(db.sp_category_report().ToList());
            }
        }
        public ActionResult Edit(int Id)
        {
            try
            {
                Category obj;
                using(Pcompany_taskEntities db = new Pcompany_taskEntities())
                {
                    var Getdata = new Category();
                    Getdata = db.Categories.Where(x => x.Id == Id).FirstOrDefault();
                    obj = new Category()
                    {
                        Id = Getdata.Id,
                        Category1= Getdata.Category1,
                    };

                }
                return View("Index", obj);
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }
        public ActionResult DELETE(int id)
        {
          
            using(Pcompany_taskEntities db = new Pcompany_taskEntities())
            {
                var Get_Data = new Category();
                Get_Data = db.Categories.Where(x => x.Id == id).FirstOrDefault();
                db.Categories.Remove(Get_Data);
                db.SaveChanges();
                var lis = db.Categories.ToList();
                return RedirectToAction("Index", lis);
               
            }
        }
        
    }
}

Pcompany_task/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pcompany_task.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Pcompany_task/Controllers/Product_MasterController.cs
using Pcompany_task.Data_Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pcompany_task.Controllers
{
    public class Product_MasterController : Controller
    {
        // GET: Product_Master
        public ActionResult Index()
        {
            ViewBag.State = Category_Data();
            return View();
        }
        public ActionResult SaveOrUpdate(Product_table model)
        {

            using (Pcompany_taskEntities db = new Pcompany_taskEntities())
            {
                if (model.Product_id == 0)
                {
                    Product_table obj = new Product_table()
                    {
                        Category_id = model.Category_id,
                        Product_name = model.Product_name,
                        Price = model.Price,
                    };
                    db.Entry(obj).State = System.Data.Entity.EntityState.Added;
                    db.SaveChanges();
                }
                else
                {
                    Product_table obj = new Product_table()
                    {
                        Product_id = model.Product_id,
                        Category_id = model.Category_id,
                        Product_name = model.Product_name,
                        Price = model.Price,
                    };
                    db.Entry(obj).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");

            }

        }

        public static List<SelectListItem> Category_Data()
        {
            var _selectList = new List<SelectListItem>();
            _selectList.Add(new SelectListItem { Value = "0", Text = "--Select--" });
            var get_State = (dynamic)null;
            try
            {
                using (Pcompany_taskEntities _Db = new Pcompany_taskEntities())
                {
                    get_State = (from x in _Db.Categories
                                 select new
                                 {
                                     x.Id,
                                     x.Category1
                                 });
                    foreach (var item in get_State)
                    {
                        _selectList.Add(new SelectListItem { Value = item.Id.ToString(), Text = item.Category1.ToString() });
                    }
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (get_State != null)
                    get_State = null;
            }
            return _selectList;
        }
        public ActionResult Report()
        {
            using (Pcompany_taskEntities db = new Pcompany_taskEntities())
            {
                ViewBag.State = Category_Data();
                return View(db.sp_product_report().ToList());
            }
        }
        public ActionResult Edit(int Id)
        {
            try
            {
                Product_table obj;
                using (Pcompany_taskEntities db = new Pcompany_taskEntities())
                {
                    var Getdata = new Product_table();
                    Getdata = db.Product_table.Where(x => x.Product_id == Id).FirstOrDefault();
                    obj = new Product_table()
                    {
                        Product_id = Getdata.Product_id,
                        Category_id = Getdata.Category_id,
                        Product_name = Getdata.Product_name,
                        Price = Getdata.Price,
                    };

                }
                ViewBag.State = Category_Data();
                return View("Index", obj);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public ActionResult DELETE(int id)
        {
            using (Pcompany_taskEntities db = new Pcompany_taskEntities())
            {
                var Get_Data = new Product_table();
                Get_Data = db.Product_table.Where(x => x.Product_id == id).FirstOrDefault();
                db.Product_table.Remove(Get_Data);
                db.SaveChanges();
                var lis = db.Product_table.ToList();
                return RedirectToAction("Index", lis);

            }
        }
    }
}

Pcompany_task/Views/Category_Master/Edit.cshtml
@model Pcompany_task.Data_Context.Category

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Category1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Pcompany_task/Views/Category_Master/Index.cshtml
@model Pcompany_task.Data_Context.Category
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Save", "Category_Master", FormMethod.Post))
{
    <div class="card-header">
        <h2>Category</h2>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <label>Category Name</label>
                @Html.TextBoxFor(m => m.Category1, new { @class = "form-control" })
                @Html.HiddenFor(m => m.Id)
                @Html.ValidationMessageFor(m => m.Category1, "", new { @class = "text-danger" })

            </div>
        </div>
    </div>
    <center><button type="submit" class="btn btn-success">Save</button></center>
}

@Scripts.Render("~/bundles/jqueryval")
@Html.Action("Report")

Pcompany_task/Views/Category_Master/Report.cshtml
@model IEnumerable<Pcompany_task.Data_Context.sp_category_report_Result>


<table class="table">
    <tr>
        <th class="bg-info text-danger">
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Category)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Pcompany_task/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Pcompany_task/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Pcompany_task/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Pcompany_task/Views/Product_Master/Index.cshtml
@model Pcompany_task.Data_Context.Product_table
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("SaveOrUpdate", "Product_Master", FormMethod.Post))
{

    <div class="card-header">
        <h2>Product</h2>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <label>Category</label>
                @Html.DropDownListFor(m => m.Category_id, new SelectList(ViewBag.State, "Value", "Text"),
                new { @class = "form-control ", onchange = "get_code()" })
                @Html.HiddenFor(m => m.Product_id)
                @Html.ValidationMessageFor(m => m.Category_id, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label>Product name</label>
                @Html.TextBoxFor(m => m.Product_name, new { @class = "form-control" })
                @Html.HiddenFor(m => m.Product_id)
                @Html.ValidationMessageFor(m => m.Product_name, "", new {@class="text-danger"})
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label>Price</label>
                @Html.TextBoxFor(m => m.Price, new { @class = "form-control" })
                @Html.HiddenFor(m => m.Product_id)
                @Html.ValidationMessageFor(m => m.Price, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-success">Save</button>
    <br />
    <br />
}
@Scripts.Render("~/bundles/jqueryval")
@Html.Action("Report")

Pcompany_task/Views/Product_Master/Report.cshtml
@model IEnumerable<Pcompany_task.Data_Context.sp_product_report_Result>
@{ 
    Layout = null;
}
<head>
    <script src="~/Content/js/datatables-simple-demo.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Content/js/scripts.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
</head>
<table id="datatablesSimple">
    <tr class="bg-primary">
        <th>
            Product Id
            @*@Html.DisplayNameFor(model => model.Product_id)*@
        </th>
        <th>
            Product Name
            @*@Html.DisplayNameFor(model => model.Product_name)*@
        </th>
        <th>
            Category Id
            @*@Html.DisplayNameFor(model => model.Category_id)*@
        </th>
        <th>
            Category Name
            @*@Html.DisplayNameFor(model => model.Category_name)*@
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Product_id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Product_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category_id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category_name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Product_id }) |

                @Html.ActionLink("Delete", "Delete", new { id = item.Product_id }, new { onclick = "return confirm('Are You Sure want To Delete?');" })
            </td>
        </tr>
    }

</table>

Pcompany_task/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <link href="~/Content/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">Start Bootstrap</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Settings</a></li>
                    <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="#!">Logout</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Category</div>
                        <a class="nav-link" href="https://localhost:44392/Category_Master/Index">

                            Category
                        </a>
                        <div class="sb-sidenav-menu-heading">Product</div>
                        <a class="nav-link" href="https://localhost:44392/Product_Master/Index">

                            Product
                        </a>
                    </div>
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2022</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Content/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="assets/demo/chart-area-demo.js"></script>
    <script src="assets/demo/chart-bar-demo.js"></script>
    <script src="~/Content/js/datatables-simple-demo.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script src="js/datatables-simple-demo.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
</body>
</html>